#PBS -N RETIPS_Use_Augments_In_Label_Classification
#PBS -l select=1:ncpus=16:mem=30gb:ngpus=1:gpu_model=v100:interconnect=any,walltime=64:00:00
#PBS -m abe
#PBS -M cehrett,kwameandre,dixizil

cd $RETIPS_ENV_APPTAINER_PATH/..

module load anaconda3/2022.10-gcc cuda/11.2.2-gcc cudnn/8.1.0.77-11.2-gcc
source activate llms_env

# Infinite loop
while true; do
    python3 Use_Augments_In_Label_Classification.py
done

